// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyByN1I2q_gVV0H7lxglHDhiKELIUZGtMAk',
    appId: '1:1086838242586:web:d72c1a5c979a90467d80a3',
    messagingSenderId: '1086838242586',
    projectId: 'smartcart-c1d29',
    authDomain: 'smartcart-c1d29.firebaseapp.com',
    storageBucket: 'smartcart-c1d29.firebasestorage.app',
    measurementId: 'G-L6DG0YK9ZT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnJa1ydOCz9hibevPvlhX9K-kJ-GL4yqo',
    appId: '1:1086838242586:android:6980e2c208b6c9007d80a3',
    messagingSenderId: '1086838242586',
    projectId: 'smartcart-c1d29',
    storageBucket: 'smartcart-c1d29.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCI3AYn4pQMKvgTdXLxmE6wGmRV1pQSdu4',
    appId: '1:1086838242586:ios:fe34b8bdaa54921e7d80a3',
    messagingSenderId: '1086838242586',
    projectId: 'smartcart-c1d29',
    storageBucket: 'smartcart-c1d29.firebasestorage.app',
    iosBundleId: 'com.example.smartCart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCI3AYn4pQMKvgTdXLxmE6wGmRV1pQSdu4',
    appId: '1:1086838242586:ios:fe34b8bdaa54921e7d80a3',
    messagingSenderId: '1086838242586',
    projectId: 'smartcart-c1d29',
    storageBucket: 'smartcart-c1d29.firebasestorage.app',
    iosBundleId: 'com.example.smartCart',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyByN1I2q_gVV0H7lxglHDhiKELIUZGtMAk',
    appId: '1:1086838242586:web:7df7b2227c4ca5e47d80a3',
    messagingSenderId: '1086838242586',
    projectId: 'smartcart-c1d29',
    authDomain: 'smartcart-c1d29.firebaseapp.com',
    storageBucket: 'smartcart-c1d29.firebasestorage.app',
    measurementId: 'G-VQ6HCP4T25',
  );
}
